spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/meetup_db"
    username: "root"
    password: "1234"

---
spring:
  config:
    activate:
      on-profile:
        - docker-compose
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:meetup_db}"
    username: "${DB_USERNAME:meetup-admin}"
    password: "${DB_PASSWORD:1234}"