CREATE SEQUENCE  IF NOT EXISTS meetup_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE meetups (
  id BIGINT NOT NULL,
   topic VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   organizer VARCHAR(255) NOT NULL,
   event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   place VARCHAR(255) NOT NULL,
   CONSTRAINT pk_meetups PRIMARY KEY (id)
);